-- MySQL Script generated by MySQL Workbench
-- Sat Nov 20 18:04:59 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema GoodBite
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema GoodBite
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GoodBite` DEFAULT CHARACTER SET utf8 ;
USE `GoodBite` ;

-- -----------------------------------------------------
-- Table `GoodBite`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GoodBite`.`Users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(32) NOT NULL,
  `password` VARCHAR(256) NOT NULL,
  `first_name` VARCHAR(32) NOT NULL,
  `last_name` VARCHAR(32) NOT NULL,
  `middle_name` VARCHAR(32) NULL,
  `address1` VARCHAR(128) NOT NULL,
  `address2` VARCHAR(128) NULL,
  `city` VARCHAR(64) NOT NULL,
  `state` VARCHAR(2) NOT NULL,
  `zipcode` VARCHAR(10) NOT NULL,
  `security_question_number` INT NOT NULL,
  `security_question_answer` VARCHAR(128) NOT NULL,
  `email` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GoodBite`.`UserPhotos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GoodBite`.`UserPhotos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `extension` ENUM('jpeg', 'jpg', 'png', 'gif') NOT NULL,
  `user_id` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `GoodBite`.`Users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GoodBite`.`UserRecipes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GoodBite`.`UserRecipes` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `ingredients` VARCHAR(1024) NOT NULL,
  `nutrition` VARCHAR(2048) NULL,
  `photo_url` VARCHAR(512) NULL,
  `instructions` LONGTEXT NULL,
  `category` VARCHAR(128) NULL,
  `cuisine` VARCHAR(128) NULL,
  `user_id` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `user_Id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `user_Id`
    FOREIGN KEY (`user_id`)
    REFERENCES `GoodBite`.`Users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GoodBite`.`GeoCodings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GoodBite`.`GeoCodings` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `zipcode` VARCHAR(10) NOT NULL,
  `lat` DECIMAL(6) NOT NULL,
  `lng` DECIMAL(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `zipcode_UNIQUE` (`zipcode` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GoodBite`.`Recipes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GoodBite`.`Recipes` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `ingredients` VARCHAR(1024) NOT NULL,
  `nutrition` VARCHAR(2048) NULL,
  `photo_url` VARCHAR(512) NULL,
  `instructions` LONGTEXT NULL,
  `category` VARCHAR(128) NULL,
  `cuisine` VARCHAR(128) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
